onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('catalog/', include('products.urls', namespace='catalog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from products.views import catalog


app_name = 'products'


urlpatterns = [
    path('', catalog, name='catalog'),
]

products/models.py
from django.db import models
from unicodedata import category


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True, default='default/default.jpg')

products/views.py
from django.shortcuts import render
from products.models import Product, Category


# Create your views here.

def index(request):
    return render(request, 'index.html')


def catalog(request):
    context = {'products': Product.objects.all(),
               'categories': Category.objects.all(),
               }
    return render(request, 'catalog.html', context=context)

users/views.py
from django.shortcuts import render

# Create your views here.

products/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="vendor/css/navbar.css" class="" />
    {% block css %} {% endblock %}
    {% block title %} {% endblock %}
  </head>
  <body>
    <!-- NAVBAR -->
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'index' %}"
                  >Главная</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalog:catalog' %}">Каталог</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">О авторе</a>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Профиль
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Профиль</a></li>
                  <li><a class="dropdown-item" href="#">Корзина</a></li>
                  <li><hr class="dropdown-divider" /></li>
                  <li>
                    <a class="dropdown-item" href="#">Админ панель</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="logo">
            <a class="navbar-brand" href="{% url 'index' %}">『CANTLISS』</a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="search">
            <form class="d-flex" role="search">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Поиск"
                aria-label="Search"
              />
              <button class="btn btn-outline-success" type="submit">
                Искать
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <!-- CONTENT -->
    <section>
      {% block content %} {% endblock %}
    </section>
      {% block footer %} {% endblock %}

    <!-- JS boostrap script -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

products/templates/catalog.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href='{% static "vendor/css/catalog.css" %}' class="" />
{% endblock %}

{% block title %}
    <title>Каталог</title>
{% endblock %}

    <!-- CONTENT -->
    <section>
      {% block content %}
        <div class="container-fluid">
          <div id="carouselExampleDark" class="carousel carousel-dark slide">
            <div class="carousel-indicators">
              <button
                type="button"
                data-bs-target="#carouselExampleDark"
                data-bs-slide-to="0"
                class="active"
                aria-current="true"
                aria-label="Slide 1"
              ></button>
              <button
                type="button"
                data-bs-target="#carouselExampleDark"
                data-bs-slide-to="1"
                aria-label="Slide 2"
              ></button>
              <button
                type="button"
                data-bs-target="#carouselExampleDark"
                data-bs-slide-to="2"
                aria-label="Slide 3"
              ></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                <img src="{% static 'vendor/slides/1.jpg' %}" class="d-block w-100" alt="..." />
                <div class="carousel-caption d-none d-md-block">
                  <p class="slide-text">Новые коллекции уже в продаже</p>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src='{% static "vendor/slides/2.jpg" %}' class="d-block w-100" alt="..." />
                <div class="carousel-caption d-none d-md-block">
                  <p class="slide-text">Модные образы по низкой цене</p>
                </div>
              </div>
              <div class="carousel-item">
                <img src='{% static "vendor/slides/3.jpg" %}' class="d-block w-100" alt="..." />
                <div class="carousel-caption d-none d-md-block">
                  <p class="slide-text">Совершай покупки с удобством</p>
                </div>
              </div>
            </div>
            <button
              class="carousel-control-prev"
              type="button"
              data-bs-target="#carouselExampleDark"
              data-bs-slide="prev"
            >
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button
              class="carousel-control-next"
              type="button"
              data-bs-target="#carouselExampleDark"
              data-bs-slide="next"
            >
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <div class="grid">
          <div class="menu-left">
            <div class="list-group">
              {% for category in categories %}
                <a href="#" class="list-group-item">{{ category.name }}</a>
              {% endfor %}
            </div>
          </div>
          <div class="container text-center">
            <div class="row">
              {% for product in products %}
                <div class="col-lg-4 col-mb-6 col-sm-12">
                  <div class="card" style="width: 18rem">
                    <img
                      src='{{ product.image.url }}'
                      class="card-img-top"
                      alt="..."
                    />
                    <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">{{ product.description }}</p>
                      <p class="card-text">{{ product.price }}$</p>
                      <a href="#" class="btn btn-primary">Купить</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endblock %}
    </section>

products/templates/index.html
{% extends 'base.html' %}
{% load static %}



{% block css %}
    <link rel="stylesheet" href='{% static "vendor/css/index.css" %}' class="" />
{% endblock %}

{% block title %}
    <title>Главная</title>
{% endblock %}
{% block content %}
      <div class="container">
        <div class="text">
          <p>Ваш универсальный ресурс для умных покупок.</p>
          <div class="button">
            <a href="catalog.html" class="">Начать покупки</a>
          </div>
        </div>
        <div class="image">
          <img src='{% static "vendor/media/pngwing.com.png" %}' alt="" class="" />
        </div>
      </div>
    </section>
{% endblock %}

{% block footer %}
      <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    </footer>
{% endblock %}